#!/bin/sh

set -e

case "$(dpkg --print-architecture)" in
	amd64)
		_SOURCE="false"
		;;

	i386)
		_SOURCE="false"
		;;
esac

lb config noauto \
        --clean \
        --ignore-system-defaults \
	--architectures amd64 \
        --mode debian \
	--system live \
	--interactive false \
	--debootstrap-options "--include=apt-transport-https,ca-certificates,openssl" \
        --mirror-bootstrap "https://deb.debian.org/debian/" \
        --mirror-chroot "https://deb.debian.org/debian/" \
        --mirror-binary "https://deb.debian.org/debian/" \
        --mirror-chroot-security "https://security.debian.org" \
	--bootloader syslinux \
	--security true \
	--updates true \
	--binary-filesystem ext4 \
	--binary-image iso-hybrid \
	--checksums sha256 \
	--debian-installer live \
	--debian-installer-gui true \
	--firmware-binary true \
	--firmware-chroot true \
	--initramfs live-boot \
	--iso-publisher Live Build \
	--iso-volume Latest \
        --bootappend-live "boot=live components toram mds=full,nosmt iommu=off selinux=1 security=selinux noacpi noefi" \
	--bootappend-live-failsafe "boot=live components toram selinux=1 security=selinux" \
        --debian-installer live \
        --linux-packages "linux-image linux-headers" \
        --archive-areas "main contrib non-free" \
        --uefi-secure-boot enable \
	--win32-loader false \
	--loadlin false \
	--memtest none \
	--zsync false \
        --source "${_SOURCE}" \
"${@}"
